[package]
name = "ckb-cli"
version = "0.1.0"
license = "MIT"
authors = ["Linfeng Qian <thewawar@gmail.com>"]
edition = "2018"

[dependencies]
# jsonrpc-sdk-prelude = "0.1.3"
jsonrpc-client-core = "0.5.0"
jsonrpc-client-http = "0.5.0"
numext-fixed-hash = "~0.1"
jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-core = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
occupied-capacity = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }

bytes = { version="0.4", features = ["serde"] }
clap = "2.33.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
ansi_term = "^0.11.0"
colored = "^1.6.0"
atty = "^0.2.10"
rustyline = "4.0.0"
shell-words = "0.1.0"
regex = "1.1.6"
dirs = "1.0.5"
url = "1.7.2"


[build-dependencies]
git2 = "0.8.0"