[package]
name = "ckb-cli"
version = "0.2.0"
license = "MIT"
authors = ["Linfeng Qian <thewawar@gmail.com>"]
edition = "2018"

[dependencies]
numext-fixed-hash = "~0.1"
jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-core = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
occupied-capacity = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
hash = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-util = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
crypto = { git = "https://github.com/nervosnetwork/ckb", branch = "develop", features = ["secp", "bech32"] }
build-info = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-sdk = { path = "ckb-sdk" }

jsonrpc-client-core = "0.5.0"
secp256k1 = {version = "0.12.2" }
faster-hex = "0.3"
env_logger = "0.6"
bytes = { version="0.4", features = ["serde"] }
crossbeam-channel = "0.3"
clap = "2.33.0"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8.9"
yaml-rust = "0.4.3"
dtoa = "0.4"
ansi_term = "^0.11.0"
colored = "^1.6.0"
atty = "^0.2.10"
rustyline = "4.0.0"
shell-words = "0.1.0"
regex = "1.1.6"
dirs = "1.0.5"
url = "1.7.2"
log = "0.4.6"
bech32 = "0.6.0"
chrono = "0.4"
rkv = "0.9.5"
bincode = "1.1.4"

[target.'cfg(unix)'.dependencies]
tui = "0.6.0"
termion = "1.5"

[build-dependencies]
build-info = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }

[workspace]
members = ["ckb-sdk"]
