[package]
name = "ckb-sdk"
version = "0.1.0"
authors = ["Linfeng Qian <thewawar@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
numext-fixed-hash = "~0.1"
bech32 = "0.6.0"
bytes = { version="0.4", features = ["serde"] }
bincode = "1.1.4"
log = "0.4.6"
rkv = "0.9.5"
# fs2 = "0.4.3"
jsonrpc-client-core = "0.5.0"
jsonrpc-client-http = "0.5.0"
rocksdb = { version = "0.12.2", default-features = false, optional = true }
secp256k1 = {version = "0.12.2" }
faster-hex = "0.3"
fnv = "1.0.3"
aes-ctr = "0.3.0"
pbkdf2 = "0.3.0"
scrypt = "0.2.0"
rand = "0.6.5"
tiny-keccak = "1.4"
byteorder = "1.3.2"
bitcoin_hashes = "0.3.2"

ckb-store = { git = "https://github.com/nervosnetwork/ckb", branch = "develop", optional = true }
ckb-db = { git = "https://github.com/nervosnetwork/ckb", branch = "develop", optional = true}
ckb-script = { git = "https://github.com/nervosnetwork/ckb", branch = "develop", optional = true }
ckb-traits = { git = "https://github.com/nervosnetwork/ckb", branch = "develop", optional = true  }
ckb-chain-spec = { git = "https://github.com/nervosnetwork/ckb", branch = "develop", optional = true  }
jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-core = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
hash = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
crypto = { git = "https://github.com/nervosnetwork/ckb", branch = "develop", features = ["secp", "bech32"] }

[features]
default = [ "rocksdb", "ckb-store", "ckb-db", "ckb-script", "ckb-traits", "ckb-chain-spec" ]